### ISSUE TITLE
Still use mini_pupper_bsp in V2

### ISSUE THREAD

**Issue by Ericsii** [mangdangroboticsclub/mini_pupper#7]
I think this should be replace to `https://github.com/mangdangroboticsclub/mini_pupper_2_bsp`

https://github.com/mangdangroboticsclub/mini_pupper/blob/361bb1c88ec2f6ea276ae757165fedfa6b1392be/v2_bsp_ros2/setup.sh#L41

**Comment by hdumcke** [comment]
I submitted a PR to address the issue.

BUT that does to mean that the setup procedure is correct. ROS2 is still an open issue and ROS1 should be retired.

Both ROS installation scripts have not been tested and you should not use them until they have been worked on.
